ROOT = '../DATA/Images/'
ROOT_MNIST = '../DATA/MNIST'
RESULT = 'results/'

#Train-Test split
TRAIN_SPLIT = 0.8
SHFFLE_DATASET = True
RANDOM_SEED = 66
#Train
BATCH_SIZE = 16
LEARNING_RATE = 0.05
MOMENTUM = 0.09
EPOCH_NUM = 50
WEIGHT_DECAY = 0.0005
STEP = 20

EPOCH_NUM_MNIST = 10